# Setup
title:               'SFWEM'
tagline:             "Intranet Resources"
description:         "This website provides on-mesh resources and links for use by Amateur Radio operators and served agencies."
url:                 http://sfwem.local.mesh
baseurl:             '/'
permalink:           pretty

# About/contact
author:
  name:              SFWEM Mesh Ops
  url:               https://sfwem.net
  email:             sfwem@undef.net

# Gems
plugin_path: [ vendor/bundle ]
plugins:
  - jekyll-paginate-v2
  - jekyll-git_metadata

# Pagination Settings
pagination:
  enabled: true
  debug: true
  per_page: 5
  collection: 'posts'
  permalink: '/page/:num/'
  title: ':title | :num of :max'
  limit: 50
  
# Custom Collections
collections:
  alerts:
  # Alerts: A Short message distributed as AREDN Alert Messages and on the site itself.
    output: true
    permalink: /alerts/:path